config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @artcile = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path

  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Wikinimous", articles_path, class: "navbar-brand" %>

      <button class="btn btn-primary">
        New article
      </button>

    </nav>

app/views/articles/index.html.erb
<div class="container">

  <div class="row">

    <%= @articles.each do |article| %>
      <div class="col-sm-6 col-md-3 mt-3 d-flex align-items-stretch">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
              <%= article.title %>
            </h5>
            <p class="card-text">
              <%= article.content %>
            </p>
            <%= link_to "Lire l'article", article_path(article) %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
      <%= @article.title %>
      </h1>
      <%= link_to "edit" %>
      <%= link_to "delete",
        article_path(@article),
        method: "delete",
        data: {confirm: "T'es sur ou bien ?"}
      %>
    <p class="lead">
      <%= @article.content %>
    </p>
  </div>
</div>
<div class="container">
  <p>
    <%= @article.content %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
  <%= render "navbar" %>

    <%= yield %>
  </body>
</html>